#ifndef CONFIG_H
#define CONFIG_H

#define DEVICE_ID "pico_w_01"

#define TASK_PRIORITY_WIFI     (configMAX_PRIORITIES - 1)
#define TASK_PRIORITY_MQTT     (configMAX_PRIORITIES - 2)
#define TASK_PRIORITY_SENSORS  (tskIDLE_PRIORITY + 1)
#define TASK_PRIORITY_DISPLAY  (tskIDLE_PRIORITY + 1)

#define TASK_STACK_WIFI   (4*1024)
#define TASK_STACK_MQTT   (6*1024)
#define TASK_STACK_SENS   (3*1024)
#define TASK_STACK_DISP   (3*1024)

#endif // CONFIG_H
